app.py
from flask import Flask  
import os

def create_app():
    app = Flask(__name__)
    app.secret_key = os.urandom( 24 )  #necesaria para atrapar todas la cookies y crear las sesiones

    from views import main
    app.register_blueprint(main)
    

    return app

views.py
from os import name
import sqlite3
from flask import Flask, render_template, blueprints, request, session, flash
from flask.helpers import url_for
from werkzeug.utils import redirect
from werkzeug.security import check_password_hash, generate_password_hash
from db import get_db
from markupsafe import escape
import random
import functools


main = blueprints.Blueprint('main', __name__) #blue prints permite separar la app en diferentes plantillas #




def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if 'session_key' not in session:#puedes hacer otro tipo de validación 
            return redirect(url_for('main.index'))
        return view(**kwargs)

    return wrapped_view

# @main.route('/prueba')
# @login_required
# def prueba():
#     return render_template('feed_prueba.html')  ## solo demostracion practica (eliminar para produccion)


# aqui se puede poner otro atributo (methods=['GET´, 'POST'])#
@main.route('/')
def index():
    return render_template('index.html')


@main.route('/hacerLogin',  methods=['POST'])
def hacerLogin():
    
    if request.method == 'POST':
        username = request.form['usuario']
        clave = request.form['clave']

        #sql = "select * from Usuario where username = '{0}' and clave = '{1}'".format(username,clave) ##0 y 1 hacen referencia a "username y clave rescpectivamente"
        db= get_db()

        user = db.execute("select * from Usuario where username = ? ",(username,)).fetchone() ##para seleccionar un usuario de la base de datos que cumpla con la criteria
        
        if user is not None:
            clave = clave + username
            sw = check_password_hash(user[7],clave)
        
            if(sw):
                session['session_key'] = user[0]
                session['username'] = user[3]
                session['nombre'] = user [1]
                session['role'] = user[8]
                if(user[8] == "user"):
                    return redirect(url_for('main.feed'))
                if(user[8] == "admin"):
                    return redirect(url_for('main.dashboard'))

        
        
        flash('Usuario o clave incorrecto.')
        
            
    return render_template('index.html') #cuando se manda get.


@main.route('/logout')
def logout():
    session.clear() #se destruye la sesion. 
    return redirect(url_for('main.index'))

@main.route('/feed/')
@login_required
def feed():

    return render_template('feed.html')


@main.route('/register/', methods=['POST','GET'])
def register():
    
    if request.method == 'POST':
        nombres = escape(request.form['nombre'])
        apellidos = escape(request.form['apellido'])
        email = escape(request.form['correo'])
        username = escape(request.form['usuario'])
        clave = escape(request.form['clave'])
        dob = escape(request.form['fecha'])
        sexo = escape(request.form['sex'])
        role = "user" 
        
        #sql= "insert into Usuario(nombres, apellidos, username, email, sexo, dob, clave) values('{0}','{1}','{2}','{3}','{4}', '{5}', '{6}')".format( nombres, apellidos, username, email , sexo, dob, clave )
        db = get_db()
        clave = clave + username # tipo de salt 
        clave= generate_password_hash(clave) #aqui se se usa el metodo para crear el hash sobre la clave
        db.execute("insert into Usuario(nombres, apellidos, username, email, sexo, dob, clave, role) values( ?, ?, ?, ? ,? ,?, ? ,?)",( nombres, apellidos, username, email ,sexo , dob, clave, role))
        db.commit()
        print("registro exitoso")
        return redirect(url_for('main.index'))

    return render_template('registro.html')
    

@main.route('/user_space/')
@login_required
def mi_espacio():
    return render_template('mi_espacio.html')


@main.route('/search_results/')
@login_required
def resultados():
    db = get_db()
    cur = db.cursor()
    sql = "SELECT * FROM Usuarios"
    cur.execute("select * from Usuario")
    info_resultados = cur.fetchall()
    cur.close
    

    return render_template('search_result.html',usuarios = info_resultados) #no se estan mostrando los resultados en el html


@main.route('/explore/')
@login_required
def explorar():
    return render_template('explorar.html')


@main.route('/admin_profile/')
@login_required
def admin_user():
    return render_template('admin_profile.html')


@main.route('/admin_dashboard/')
@login_required
def dashboard():
    return render_template('dashboard.html')


@main.route('/messages/')
@login_required
def mensajes():
    return render_template('mensajes.html')


@main.route('/alerts/')
def notificaciones():
    return render_template('notificaciones.html')


@main.route('/new_post/')
@login_required
def post():
    return render_template('nuevo_post.html')


@main.route('/user_profile/')
@login_required
def perfil_user():
    return render_template('user_profile.html')


@main.route('/new_password/')
@login_required
def newpass():
    return render_template('cambPassword.html')


@main.route('/suggestions/')
@login_required
def relacionate():
    return render_template('relacionate.html')

templates/base.html
<html lang="sp">
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cairina Moschata</title>
    <link rel="shortcut icon"  href="../static/img/favicon.png">
    <link rel="stylesheet" href="../static/fontawasome/css/all.min.css">
    {% block estilos %} <!--<link rel="stylesheet" type="text/css" media="screen" href="../static/css/feed.css" /-->{% endblock %}


</head>
    <body>

        <div id ="barra_estado">
            <div id="ctn-bars-search"> <!--search-input-->
                <a href="" target="_blank" hidden></a>
                    <input type="text" id="inputSearch" placeholder="¿buscas a alguien? Escribe su nombre aquí" > <!--id="inputSearch"-->
                    
                    <div id="ctn-icon-search" > <a href="{{url_for('main.resultados')}}"><i class="fas fa-search" id="icon-search"></i></a><!----> <!--id="icon-search"-->
                    </div>
                    <ul id ="box-search"> 
                        <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> luisa</a></a></li>
                        <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> leo</a></a></li>
                        <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> shakira</a></a></li>
                        <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> marco</a></a></li>
                        <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> daniela</a></a></li>
                        <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> jbalvin</a></a></li>
                        
                    </ul>
                    <!--<div class="icon"><i class="fas fa-search"></i></div>-->
                </div>

        
            <!--<h2 class="icon_text">Cairina Moschata</h2> cambiar imagen a una con icono y letras-->
            <a href="{{url_for('main.feed')}}" > <img src="{{ url_for('static', filename='/img/icon_cairina.jpg') }}" class="btn_icon" alt="icono de cairina"></a>
            <a href="{{url_for('main.feed')}}" > <img src="{{ url_for('static', filename='/img/texto_logo_2.png') }}" class="txt_icon" alt="icono de cairina"></a>


            <!-- <a href="{{url_for('main.notificaciones')}}" id="btn_notification"><i class="fas fa-bell"></i></a> -->
            <a href="{{url_for('main.logout')}}" id="btn_logout"><i class="fas fa-sign-out-alt"></i></a>
            <a href="{{url_for('main.mensajes')}}" id="btn_message"> <i class="fas fa-envelope"></i></a>
            <a href="{{url_for('main.perfil_user')}}" id="btn_user"><i class=" fas fa-user-circle"></i></i></a>
            <!-- En el div barra_estado se usan anchors en forma de botones para utilizar iconos de fontawesome
            es necesario tener las carpetas "svgs y webfonts" dentro del proyecto para que funcionen y utilizar un link como 
            se muestra en la linea 10 .....En la clase wrapper se encuenta todo lo relacionado a la barra de busqueda-->
        
        </div>

        {% block contenido %}
        
        
        
        {% endblock %}


        <div class="footer">
            <div class="footer-links">

              <a href="#">Terms of Use</a> | 

              <a href="#">Privacy Policy</a> | 

              <a href="#">Developers</a> | 

              <a href="#">Contact</a> | 

              <a href="#">About</a>
              <h3>Copyright © Company - All rights reserved</h3>
        </div>   
            
                   
    {% block scripts %}<!--<script src="../static/js/buscador.js"> </script>--> 
    {% endblock %}
    </body>
</html>

templates/cambPassword.html
{% extends 'base.html'%}

{% block estilos %}
<meta name="theme color" content="#C991D8">
<link rel="stylesheet" type="text/css" media="screen" href="../static/css/feed.css" />
<link rel="stylesheet" href="{{ url_for('static', filename='css/password.css') }}">

{% endblock %}
<!-- <title> username V (@username)| Fotos y videos de Cairina Moschata </title> -->

{% block scripts %}
<script src="https://kit.fontawesome.com/25598d9e09.js" crossorigin="anonymous"></script>
<script src="js/profile.js"> </script>  
<script src="../static/js/buscador.js"> </script>

{% endblock %}
    

{% block contenido %} 
        
        <br>
        <br>
        <br>
        <br>

        <div>
            <h4 id=mapa> 
                <a href="/feed/">Inicio </a>
                <a href="/admin_profile/">Perfil  </a>
                <a href="/user_profile/">Editar perfil  </a>
                <a href="/new_password/">Cambio de contraseña  </a></h4>
            <table>
                <thead>
                    <tr>
                        <td>00</td>
                        <td>00</td>
                        <td>00</td>
                    </tr>
                </thead>
                <td> Publicaciones </td>
                <td>  Seguidores  </td>
                <td>  Seguidos  </td>
            </table>
        </div>

        <div class="h2opciones"> 
            <div class="hlargo">
                <h3><a href="/user_profile/" class="user_photo"><i id= us2 class="fas fa-user-circle" ></i> Nombre de usuario </a> 
                </h3>       
            </div>

        <form name="camContras" method="POST" action=""> 
        <p> Cambiar contraseña</p>
        <input id="nom" type="tex" name="nombre" style="width: 460px; height: 30px;">  </p>
        <p> Activar verificación en dos pasos <sytle= font font-weight bold>  </sytle=>
            <input id="nombre" type="tex" name="verificarcorreo" style="width: 460px; height: 30px;" style="padding: 20%;"><br> <br>
            <input id="nombre1" type="tex" name="verificartelefono" style="width: 460px; height: 30px;" style="padding-top: 22%;">  </p> 
            
            <p> Verificar correo electrónico <sytle= font font-weight bold>  </sytle=>
                <input id="nom" type="tex" name="nombre" style="width: 460px; height: 30px;" style="padding: 6%;">
            
            <p> Verificar número telefónico <sytle= font font-weight bold>  </sytle=>
                <input id="nom" type="tex" name="nombre" style="width: 460px; height: 30px;" style="padding: 6%;">
       
            <button id="btn"> Activar </button>
{% endblock %}

templates/explorar.html
    {% extends 'base.html'%}

    {% block estilos %}
    <link rel="stylesheet" type="text/css" media="screen" href="../static/css/feed.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="../static/css/explorar.css" />
    {% endblock %}
    
    {% block scripts %}<script src="../static/js/buscador.js"> </script> {% endblock %}
    
    {% block contenido %}
    
    <div class="nav_menu">
        <a href="{{url_for('main.feed')}}">Inicio</a> | 

        <a href="{{url_for('main.post')}}">Nuevo Post</a> |   

        <a href="{{url_for('main.mi_espacio')}}">Tu espacio</a> | 

        <a href="{{url_for('main.relacionate')}}">Relacionate</a>

    </div>
    <h3 class="amigos">Los mas populares están aquí</h3>

    <div class="resultado_busqueda"> <!--""-->
        <img src="../static/img/shakira.jpg" alt="foto de varias personas tomandose una selfie">
        <img src="../static/img/leomessi.jpg" alt="foto de hombre jugando futbol">
        <img src="../static/img/jbalvin.jpg" alt="foto de mujer en la playa">
    </div>
    {% endblock %}

templates/feed.html
<!DOCTYPE html>
<html lang="sp">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cairina Moschata</title>
    <link rel="shortcut icon"  href="../static/img/favicon.png">
    <link rel="stylesheet" type="text/css" media="screen" href="../static/css/feed.css" />
    <link rel="stylesheet" href="../static/fontawasome/css/all.min.css">
</head>
<body>
    <div id ="barra_estado"> 
        
        <div id="ctn-bars-search"> <!--search-input-->
            <a href="" target="_blank" hidden></a>
                <input type="text" id="inputSearch" placeholder="¿buscas a alguien? Escribe su nombre aquí" > <!--id="inputSearch"-->
                
                <div id="ctn-icon-search" > <a href="{{url_for('main.resultados')}}"><i class="fas fa-search" id="icon-search"></i></a><!----> <!--id="icon-search"-->
                </div>
                <ul id ="box-search"> 
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> luisa</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> leo</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> shakira</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> marco</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> daniela</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> jbalvin</a></a></li>
                    
                </ul>
                <!--<div class="icon"><i class="fas fa-search"></i></div>-->
            </div>

       
        <!--<h2 class="icon_text">Cairina Moschata</h2> cambiar imagen a una con icono y letras-->
        <a href="{{url_for('main.feed')}}" > <img src="{{ url_for('static', filename='/img/icon_cairina.jpg') }}" class="btn_icon" alt="icono de cairina"></a>
        <a href="{{url_for('main.feed')}}" > <img src="{{ url_for('static', filename='/img/texto_logo_2.png') }}" class="txt_icon" alt="icono de cairina"></a>


        <a href="{{url_for('main.notificaciones')}}" id="btn_notification"><i class="fas fa-bell"></i></a>
        <a href="{{url_for('main.index')}}" id="btn_logout"><i class="fas fa-sign-out-alt"></i></a>
        <a href="{{url_for('main.mensajes')}}" id="btn_message"> <i class="fas fa-envelope"></i></a>
        <a href="{{url_for('main.perfil_user')}}" id="btn_user"><i class=" fas fa-user-circle"></i></i></a>
         <!-- En el div barra_estado se usan anchors en forma de botones para utilizar iconos de fontawesome
        es necesario tener las carpetas "svgs y webfonts" dentro del proyecto para que funcionen y utilizar un link como 
        se muestra en la linea 10 .....En la clase wrapper se encuenta todo lo relacionado a la barra de busqueda-->
      
    </div>
    

    
    <div id ="titulo">
        <h1 id="feed_title">Usuario, ¿A dónde vamos? </h1>
    </div>
    
    
    
    <div class="contenido">
         <!-- se utilizan 4 divs dentro de contenido, que a su vez contienen las imagenes para poder darles estilos de manera 
        eficiente.... se utilizan anchors como botones para linkear otras vistas -->
        
        <div class="square_post">
            <img class="img_post" src="../static/img/nuevo_post.jpg" alt="imagen de una persona fotofrageando a su perro">
            <a href="{{url_for('main.post')}}" class="btn_post"><h4>Nuevo Post</h4></a>
        </div>
        <div class="square_explore">
            <img class="img_explore" src="../static/img/explorar.jpg" alt="foto de personas viendo el celular">
            <a href="{{url_for('main.explorar')}}" class="btn_explore" ><h4>Explorar</h4></a>
        </div>
        <div class="square_space">
            <img class="img_space" src="../static/img/mi_espacio.jpg" alt="foto de amigos reunidos">
            <a href="{{url_for('main.mi_espacio')}}" class="btn_space"><h4>Mi Espacio</h4></a>
        </div>
        <div class="square_connect">
            <img class="img_connect" src="../static/img/relacionate.jpg" alt="foto de personas conociendose">
            <a href="{{url_for('main.relacionate')}}" class="btn_connect"><h4>Relacionate</h4></a>
        </div>
    </div>

    <div class="footer">
                <div class="footer-links">
  
                  <a href="#">Terms of Use</a> | 
  
                  <a href="#">Privacy Policy</a> | 
  
                  <a href="#">Developers</a> | 
  
                  <a href="#">Contact</a> | 
  
                  <a href="#">About</a>
                  <h3>Copyright © Company - All rights reserved</h3>
                </div>   
                
                       
  

    </div>

    <!--<Script src="../static/js/feed.js"></Script>
    <Script>src="../static/js/susggestions.js"</Script>-->

    <script src="../static/js/buscador.js"> </script>

</body>
</html>

templates/feed_prueba.html
{% extends 'base.html'%}

{% block estilos %} <link rel="stylesheet" type="text/css" media="screen" href="../static/css/feed.css" />{% endblock %}

{% block scripts %}<script src="../static/js/buscador.js"> </script> {% endblock %}

{% block contenido %}
<div id ="titulo">
    <h1 id="feed_title"> {{session['nombre']}}, ¿A donde vamos hoy?</h1>  <!--se agrego session  ¿A dónde vamos?-->
    <p></p>
</div>

<div class="contenido">
     <!-- se utilizan 4 divs dentro de contenido, que a su vez contienen las imagenes para poder darles estilos de manera 
    eficiente.... se utilizan anchors como botones para linkear otras vistas -->
    
    <div class="square_post">
        <img class="img_post" src="../static/img/nuevo_post.jpg" alt="imagen de una persona fotofrageando a su perro">
        <a href="{{url_for('main.post')}}" class="btn_post"><h4>Nuevo Post</h4></a>
    </div>
    <div class="square_explore">
        <img class="img_explore" src="../static/img/explorar.jpg" alt="foto de personas viendo el celular">
        <a href="{{url_for('main.explorar')}}" class="btn_explore" ><h4>Explorar</h4></a>
    </div>
    <div class="square_space">
        <img class="img_space" src="../static/img/mi_espacio.jpg" alt="foto de amigos reunidos">
        <a href="{{url_for('main.mi_espacio')}}" class="btn_space"><h4>Mi Espacio</h4></a>
    </div>
    <div class="square_connect">
        <img class="img_connect" src="../static/img/relacionate.jpg" alt="foto de personas conociendose">
        <a href="{{url_for('main.relacionate')}}" class="btn_connect"><h4>Relacionate</h4></a>
    </div>
</div> 
        
{% endblock %}

templates/index.html
<html>

<head>
  <title>Cairina | Login</title>
  <meta charset="UTF-8">
  <link rel="stylesheet" type="text/css" href="../static/css/miEstiloLogIn.css">
  <link rel="shortcut icon" href="../static/img/favicon.png">
  <!-- <script type="text/javascript" src="../static/js/LogIn.js"></script> -->
</head>

<body>
  

  <div class="login-page">
    <div class="row">
      <!--<h1>Cairina Moschata</h1> -->
      <form role="form" class="frm  animated flipInX" name="formularioLogin" action="hacerLogin" method="post">
        <img src="../static/img/LogoConNombre.png" class="user-avatar">

        <div class="form-content">

          <div>

            <input type="text" class="form-control input-underline input-lg" placeholder="Username" name="usuario">
            <span class="error" id="errorusuario"></span>

          </div>

          <div>

            <input type="password" class="form-control input-underline input-lg" placeholder="Password" name="clave">
            <span class="error" id="errorClave"></span>

          </div>

        </div>

        <div>
          <p> 
            {% with mensajes = get_flashed_messages() %}
              {% if mensajes %}
                {% for m in mensajes %}
                  <div class="error.msm"> {{ m }} </div>
                {% endfor %}
              {% endif %}
            {% endwith%}
          </p>



          <!--
                <button type="submit" id="botonLogIn" onclick="return validar()" >Log in</button>
                <a href="../html/registro.html" class="btn_registro"><h4>Registrarse</h4></a>
                <button type="submit" id="botonRegistro">Registrate</button>-button >Registrase</button>
              <a href="../html/registro.html" class="btn_registro">registrarse</a>-->

          <button type="submit" id="botonLogIn" onclick="return validar()" >Log in</button>
          <a href="{{url_for('main.register')}}" class=" btn_registro"><input type="button" value="Registrarse"></a>

          <p> </p>
        </div>

        <a href="#" class="footer-links">Olvidé mi contraseña</a>

      </form>
    </div>



    <div class="row">

      <div class="container">

        <p></p>

        <div class="footer-links">

          <a href="#">Terms of Use</a> |

          <a href="#">Privacy Policy</a> |

          <a href="#">Developers</a> |

          <a href="#">Contact</a> |

          <a href="#">About</a>

        </div>

        Copyright © Company - All rights reserved

        <p></p>

      </div>

    </div>

  </div>
  {% with mensajes = get_flashed_messages() %}
    {% if mensajes %}
      {% for m in mensajes %}
        <div class="error.msm"> {{ m }} </div>
      {% endfor %}
    {% endif %}
  {% endwith%}
</body>

</html>

templates/notificaciones.html
<!DOCTYPE html>
<html lang="sp">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cairina Moschata</title>
</head>
<body>
    <h1>notificaciones</h1>
    
</body>
</html>

templates/relacionate.html
    
    {% extends 'base.html'%}

    {% block estilos %}
    <link rel="stylesheet" type="text/css" media="screen" href="../static/css/feed.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="../static/css/relacionate.css" />
    {% endblock %}
    
    {% block scripts %}<script src="../static/js/buscador.js"> </script> {% endblock %}
    
    {% block contenido %}
    
    <div class="nav_menu">
        <a href="{{url_for('main.feed')}}">Inicio</a> | 

        <a href="{{url_for('main.post')}}">Nuevo Post</a> |   

        <a href="{{url_for('main.explorar')}}">Explorar</a> | 

        <a href="{{url_for('main.mi_espacio')}}">Mi espacio</a>

    </div>
    <h3 class="amigos">¿los conoces? ¡siguelos!</h3>

    <div class="resultado_busqueda"> <!--""-->
        <img src="../static/img/siguelos.jpg" alt="foto de varias personas tomandose una selfie">
    </div>

    {% endblock %}
    

templates/search_result.html
    {% extends 'base.html'%}

    {% block estilos %}
    <link rel="stylesheet" type="text/css" media="screen" href="../static/css/feed.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="../static/css/search_result.css" />
    {% endblock %}
    
    {% block scripts %}<script src="../static/js/buscador.js"> </script> {% endblock %}
    
    {% block contenido %}

    <div class="nav_menu">
        <a href="{{url_for('main.feed')}}">Inicio</a> | 

        <a href="{{url_for('main.post')}}">Nuevo Post</a> |   

        <a href="{{url_for('main.explorar')}}">Explorar</a> | 

        <a href="{{url_for('main.mi_espacio')}}">Tu espacio</a> |

        <a href="{{url_for('main.relacionate')}}">Relacionate</a>
    </div>

    <h3 class="resultados">Resultados:</h3>

    <div class="resultado_busqueda"> <!--""-->
        <h5> No se encontraron resultados :(</h5>
        <!-- <p>
            <Table>
                <thead>
                    <tr>
                        <td> Usuarios encontrados</td>
                        <td> Acciones </td>
                    </tr>

                </thead>
                <tbody>
                    {%for usuario in usuarios%}
                        <tr>
                            <td>{{usuario.1 +" "+ usuario.2}} </td>
                            
                        </tr>

                    {% endfor %}

                </tbody>
            </Table> -->

            Esto es una prueba para mostrar el funcionamiento del scroll bar!!!!.
            <br>
            <br>
            Aqui Va desplegada la lista de usuarios encontrados teniendo en cuenta los criterios de busqueda
            <br>
            <br>
            
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti consectetur minus deleniti culpa ducimus alias blanditiis, suscipit eligendi vel quam magni ad quasi iure? Nulla dolorum repellat atque laboriosam. Vel?
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Corrupti sequi provident expedita esse, nostrum corporis reiciendis, vel odio laboriosam dolorum distinctio totam, soluta delectus dolores vero. Eum libero laborum sunt. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Corrupti sequi provident expedita esse, nostrum corporis reiciendis, vel odio laboriosam dolorum distinctio totam, soluta delectus dolores vero. Eum libero laborum sunt.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Corrupti sequi provident expedita esse, nostrum corporis reiciendis, vel odio laboriosam dolorum distinctio totam, soluta delectus dolores vero. Eum libero laborum sunt. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Corrupti sequi provident expedita esse, nostrum corporis reiciendis, vel odio laboriosam dolorum distinctio totam, soluta delectus dolores vero. Eum libero laborum sunt.
      </p>
    </div>

    {% endblock %}
   

templates/user_profile.html
{% extends 'base.html'%}

{% block estilos %}
<meta name="theme color" content="#C991D8">
<link rel="stylesheet" type="text/css" media="screen" href="../static/css/feed.css" />
<link rel="stylesheet" href="{{ url_for('static', filename='css/perfil.css') }}">

{% endblock %}
<!-- <title> username V (@username)| Fotos y videos de Cairina Moschata </title> -->

{% block scripts %}
<script src="https://kit.fontawesome.com/25598d9e09.js" crossorigin="anonymous"></script>
<script src="js/profile.js"> </script>  
<script src="../static/js/buscador.js"> </script>

{% endblock %}
    

{% block contenido %} 
    
<br>
<br>
<br>
<br>

<div>
    <h4 id=mapa> 
    <a href="/feed/">Inicio </a>
    <a href="/user_profile/">Perfil  </a>
    </h4>
    
    <table>
        <thead>
            <tr>
                <td>00</td>
                <td>00</td>
                <td>00</td>
            </tr>
        </thead>
        <td> Publicaciones </td>
        <td>  Seguidores  </td>
        <td>  Seguidos  </td>
    </table>
</div>

<div class="h2opciones"> 
    <div class="hlargo">
        <h3><a href="/user_profile/" class="user_photo" > <i id= us class="fas fa-user-circle"></i> </a> Nombre de usuario 
            <p style="position: img/down; text-align: down; font-size: medium; font-weight: bold"> Nombre Completo </p> </h3> </div>
    <div class="textoPerfil">
           <p>Aquí se visualiza tu biografía</p>
    </div>
    <hr id="lineal">
</div>
<a href="/user_profile/"> <button id=btnEditText type="submit"> Edita tu perfil</button></a>
<br>
<br>
<a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> luisa</a>
<a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> marco</a>
<div class="imagenes">     
<img class="img_admin_profile" src="../static/img/Gente seguida.jpg" alt="personas que sigues" style="width: 40%; height: 60%;">
<img class="img_admin_profile" src="../static/img/Etiquetar personas.jpg" alt="etiquetar personas"style="width: 30%;height: 50%;" >
<img class="img_admin_profile" src="../static/img/seguir.png" alt="seguir a una persona"style="width: 25%; height: 50%;" >
</div>

 
 {% endblock %}